######################## default configuration ####################
baseURL = "https://www.mzmc.com.cn/"
title = "MZMC - China Food & Agriculture Market Development"
theme = "mzmc"
metaDataFormat = "yaml"
# post pagination
[pagination]
pagerSize = 6
# post excerpt
summaryLength = "10"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disqus short name
[services.disqus]
shortname = ""


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
# [[params.plugins.css]]
# link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome6/css/all.min.css"
[[params.plugins.css]]
link = "plugins/animate.css"
[[params.plugins.css]]
link = "plugins/prettyPhoto.css"
[[params.plugins.css]]
link = "plugins/owl/owl.carousel.css"
[[params.plugins.css]]
link = "plugins/owl/owl.theme.css"
[[params.plugins.css]]
link = "plugins/flex-slider/flexslider.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.min.css"
[[params.plugins.css]]
link = "plugins/cd-hero/cd-hero.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/gsap/TweenMax.min.js"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/owl/owl.carousel.js"
[[params.plugins.js]]
link = "plugins/jquery.prettyPhoto.js"
[[params.plugins.js]]
link = "plugins/flex-slider/jquery.flexslider.js"
# [[params.plugins.js]]
# link = "plugins/cd-hero/cd-hero.js"
[[params.plugins.js]]
link = "plugins/isotope.js"
[[params.plugins.js]]
link = "plugins/ini.isotope.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/jquery.easing.1.3.js"
[[params.plugins.js]]
link = "plugins/jquery.counterup.min.js"
[[params.plugins.js]]
link = "plugins/waypoints.min.js"
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.min.js"
[[params.plugins.js]]
link = "plugins/scrollmagic/uncompressed/ScrollMagic.js"
[[params.plugins.js]]
link = "plugins/scrollmagic/uncompressed/plugins/jquery.ScrollMagic.js"
[[params.plugins.js]]
link = "plugins/scrollmagic/uncompressed/plugins/animation.gsap.js"
#[[params.plugins.js]]
#link = "plugins/scrollmagic/uncompressed/plugins/animation.velocity.js"
[[params.plugins.js]]
link = "plugins/svg-injector.min.js"
[[params.plugins.js]]
link = "plugins/lazyload.min.js"



############################## English navigation ###############################

[[Languages.en.menu.main]]
name = "Services"
URL = "services"
weight = 1

[[Languages.en.menu.main]]
name = "Company"
weight = 5
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Company"
  name = "About"
  URL = "about"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "Company"
  name = "Team"
  URL = "team"
  weight = 5

  [[Languages.en.menu.main]]
  parent = "Company"
  name = "News"
  URL = "news"
  weight = 10

  [[Languages.en.menu.main]]
  parent = "Company"
  name = "Careers"
  URL = "careers"
  weight = 15

#  [[Languages.en.menu.main]]
#  parent = "Company"
#  name = "FAQ"
#  URL = "faq"
#  weight = 20

[[Languages.en.menu.main]]
name = "Clients"
URL = "clients"
weight = 10

[[Languages.en.menu.main]]
name = "Case Studies"
URL = "case-studies"
weight = 15

# [[Languages.en.menu.main]]
# name = "Media"
# URL = "produce-report"
# weight = 20

# [[Languages.en.menu.main]]
# weight = 5
# name = "Pages"
# hasChildren = true

#  [[Languages.en.menu.main]]
#  parent = "Pages"
#  name = "Pricing"
#  URL = "pricing"

[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 25


#################### default parameters ################################
[params]
logo = "images/MZMC_logo_horizontal_RGB.png"
# home = "Home"
# Meta data
description = "MZMC is the China market development partner for global food and agricultural producers"
author = "MZMC"
# contact info
address = "Shanghai, China"
phone = "+86 21-6521-6751"
email = "info[at]mzmc.com.cn"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# copyright
copyright = "Copyright &copy; 2022 MZMC"

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "31.26545"
map_longitude = "121.49086"
map_marker = "images/marker.png"
  
############################# social site ########################
[[params.social]]
name = "linkedin"
icon = "fa-brands fa-linkedin" # fontawesome icon pack 6.1.2
link = "https://www.linkedin.com/company/mzmc/"

[[params.social]]
name = "twitter"
icon = "fa-brands fa-twitter" # fontawesome icon pack 6.1.2
link = "https://twitter.com/ProduceReport"

[[params.social]]
name = "facebook"
icon = "fa-brands fa-facebook" # fontawesome icon pack 6.1.2
link = "https://www.facebook.com/ProduceReport"

[[params.social]]
name = "wechat"
icon = "fa-brands fa-weixin" # fontawesome icon pack 6.1.2
link = "https://guojiguoshu.com/webform/905"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[Languages.en.params]
# footer content
footer_content = ""
# copyright
copyright = "Copyright &copy; MZMC"

################################### Taxonomies #####################################
